import Head from "next/head";
import HomeComponent from "../src/components/HomeComponent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Revel codes chellange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeComponent />
    </div>
  );
}
